version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ims
      POSTGRES_PASSWORD: ims123
      POSTGRES_DB: imsdb
    ports:
      - "5432:5432"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"
